# Copyright 2023-2026 NXP
# SPDX-License-Identifier: BSD-2-Clause
## @package legalDisclaimer
#
# The module which generates legal information about the current project
from datetime import date
import os


def get_copyright(filename):
    """
    A simple wrapper around a file used to generate copyright and
    auto‑generated notices.

    Args:
        filename (str): Name of the file into which the copyright
            and generated comments will be written.

    Returns:
        str: The generated copyright string.
    """
    string = """/*=============================================================================================*/
/* Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.               */
/* See https://llvm.org/LICENSE.txt for license information.                                   */
/*                                                                                             */
/* SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception                                     */
/* This file is generated by make_td tool as part of Tristan Project, DO NOT EDIT IT DIRECTLY! */
/*=============================================================================================*/
\n\n"""
    list_dir = list()
    for fname in os.listdir("."):
        list_dir.append(fname)
    if os.path.exists(filename) is False:
        f = open(filename, "x")
        f.close()
    f = open(filename, "w")
    f.write(string)
    f.close()

def get_copyright_len():
    """
    Returns the string used to determine its length for copyright
    and generated-comment handling.

    Returns:
        str: A string whose length is used for formatting or validation.
    """
    string = """/*=======================================================================================*/
/* Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.         */
/* See https://llvm.org/LICENSE.txt for license information.                             */
/* SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception                               */
/* This file is generated, DO NOT EDIT IT DIRECTLY!                                      */
/*=======================================================================================*/
\n\n"""
    return string


def get_generated_file(filename):
    """
    A simple wrapper for a file, used to generate a basic "generated" marker string.

    Args:
        filename (str): Name of the file into which the generated marker
            or metadata will be written.

    Returns:
        str: A basic generated-string marker.
    """
    string = """"""
    list_dir = list()
    for fname in os.listdir("."):
        list_dir.append(fname)
    if "tools" not in list_dir:
        if filename.startswith("./"):
            filename = "." + filename
            f = open(filename, "a")
            f.write(string)
            f.close()
        else:
            f = open(filename, "w")
            f.write(string)
            f.close()
    else:
        f = open(filename, "a")
        f.write(string)
        f.close()


def get_generated_file_len():
    """
    Returns the string used to determine its length for the generated-file marker.

    Returns:
        str: A string used to compute the length of the generated-file marker.
    """
    string = """
// This file is generated, DO NOT EDIT IT DIRECTLY!\n
"""
    return string

def add_sail_license(filename):
    string = """/*=======================================================================================*/
/*  This Sail RISC-V architecture model, comprising all files and                        */
/*  directories except where otherwise noted is subject the BSD                          */
/*  two-clause license in https://github.com/riscv/sail-riscv/blob/master/LICENCE.       */
/*                                                                                       */
/*  SPDX-License-Identifier: BSD-2-Clause                                                */
/*  This file is generated by make_td tool as part of Tristan Project                    */
/*=======================================================================================*/
"""
    list_dir = list()
    for fname in os.listdir("."):
        list_dir.append(fname)
    if "tools" not in list_dir:
        if filename.startswith("./"):
            filename = "." + filename
            f = open(filename, "w")
            f.write(string)
            f.close()
        else:
            f = open(filename, "w")
            f.write(string)
            f.close()
    else:
        f = open(filename, "w")
        f.write(string)
        f.close()